# Generated by Django 2.1.2 on 2018-10-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharacterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Character')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.City')),
            ],
        ),
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('SessionDate', models.DateTimeField()),
                ('RegionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TownCryer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.CharField(max_length=5000)),
                ('SessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Session')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.World'),
        ),
        migrations.AddField(
            model_name='cityitem',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Item'),
        ),
        migrations.AddField(
            model_name='city',
            name='RegionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Region'),
        ),
        migrations.AddField(
            model_name='charitem',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Item'),
        ),
        migrations.AddField(
            model_name='charactersession',
            name='SessionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Session'),
        ),
    ]
