# Generated by Django 2.1.2 on 2018-12-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharName', models.CharField(max_length=40)),
                ('Class', models.CharField(choices=[('BARBARIAN', 'Barbarian'), ('BARD', 'Bard'), ('CLERIC', 'Cleric'), ('DRUID', 'Druid'), ('FIGHTER', 'Fighter'), ('MONK', 'Monk'), ('PALADIN', 'Paladin'), ('RANGER', 'Ranger'), ('ROGUE', 'Rogue'), ('SORCERER', 'Sorcerer'), ('WARLOCK', 'Warlock'), ('WIZARD', 'Wizard')], max_length=20)),
                ('Level', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CharItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Character')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.City')),
            ],
        ),
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('Time', models.DateTimeField()),
                ('GM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='westmarchSite.GM')),
                ('RegionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TownCrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField()),
                ('PublishDate', models.DateTimeField()),
                ('SessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Session', verbose_name='Game name')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.World'),
        ),
        migrations.AddField(
            model_name='cityitem',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Item'),
        ),
        migrations.AddField(
            model_name='city',
            name='RegionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Region'),
        ),
        migrations.AddField(
            model_name='charitem',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Player'),
        ),
    ]
