# Generated by Django 2.1.2 on 2018-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Bio',
            field=models.CharField(max_length=1028, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='BioShort',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
