# Generated by Django 2.1.2 on 2018-10-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='SessionDate',
        ),
    ]
