# Generated by Django 2.1.2 on 2018-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0002_auto_20181207_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Bio',
            field=models.TextField(null=True, verbose_name='Full Bio'),
        ),
        migrations.AlterField(
            model_name='character',
            name='BioShort',
            field=models.CharField(max_length=120, null=True, verbose_name='Short description'),
        ),
    ]
