# Generated by Django 2.1.2 on 2018-10-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0002_remove_session_sessiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towncryer',
            name='Link',
        ),
    ]
