# Generated by Django 2.1.2 on 2018-10-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0003_remove_towncryer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towncryer',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='towncryer',
            name='SessionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Session', verbose_name='Game name'),
        ),
    ]
