# Generated by Django 2.1.2 on 2018-10-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0004_auto_20181013_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TownCryer',
            new_name='TownCrier',
        ),
    ]
