# Generated by Django 2.1.2 on 2018-10-21 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0005_auto_20181013_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='towncrier',
            name='PublishDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
