# Generated by Django 2.1.2 on 2018-10-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('westmarchSite', '0007_auto_20181021_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('GM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='westmarchSite.GM')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Region')),
            ],
        ),
        migrations.RemoveField(
            model_name='charactersession',
            name='CharacterID',
        ),
        migrations.RemoveField(
            model_name='charactersession',
            name='SessionID',
        ),
        migrations.AddField(
            model_name='character',
            name='PlayerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Player'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterSession',
        ),
        migrations.AddField(
            model_name='character',
            name='PartyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='westmarchSite.Party'),
            preserve_default=False,
        ),
    ]
